using System;

namespace Client.View
{
	/// <summary>
	/// User interaction events.
	/// These are used to signal to the controller that different stuff should happen.
	/// </summary>
	public enum UserEvent
	{
		ACCOUNT_CREATE_CHARACTER,
		ACCOUNT_DELETE_CHARACTER,
		ACCOUNT_SHOW_DEFAULT,
		ACCOUNT_SHOW_DELETE_CHARACTER,
		ACCOUNT_SHOW_DELETING,
		ACCOUNT_PLAY,
		ACCOUNT_QUIT,
		LAUNCHER_LOGIN,
		LAUNCHER_REGISTER,
		LAUNCHER_SHOW_LOGIN,
		LAUNCHER_SHOW_REGISTRATION,
		LAUNCHER_QUIT,
		MAIN_SHOW,
		MAIN_QUIT,
		MAIN_SEND_CHAT,
		MAP_CONTEXT,
		MAP_LOAD,
		MAP_MOVE_CHARACTER,
		MAP_SHOW_DEFAULT,
		MAP_TRAVEL,
		MAIN_HUNT,
		SERVER_POLL_DATA,
		WINDOW_QUIT,
		CHARACTER_SHOW,
		CHARACTER_TRAIN_STRENGTH,
		CHARACTER_TRAIN_ENDURANCE,
		CHARACTER_TRAIN_AGILITY,
		CHARACTER_TRAIN_INTELLIGENCE,
		CHARACTER_TRAIN_PERCEPTION,
		CHARACTER_TRAIN_WILLPOWER,
		UPDATE_CURRENT_PAGE
	}
}

